"""empty message

Revision ID: 0180c01c4b92
Revises: 1a801873d7e3
Create Date: 2023-01-10 10:05:06.470594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0180c01c4b92'
down_revision = '1a801873d7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('updating_status', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'updating_status')
    # ### end Alembic commands ###
