"""empty message

Revision ID: 033e2affbe9b
Revises: 98483fce4bb3
Create Date: 2022-08-17 18:38:47.703530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033e2affbe9b'
down_revision = '98483fce4bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('maintainer', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'maintainer')
    # ### end Alembic commands ###
