"""empty message

Revision ID: 0a1aea321a20
Revises: 7f60656dbef4
Create Date: 2022-08-18 01:51:39.401478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1aea321a20'
down_revision = '7f60656dbef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_to_course', 'is_first_part')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_to_course', sa.Column('is_first_part', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
