"""empty message

Revision ID: 1773a9ed2283
Revises: 33c87310b018
Create Date: 2023-03-09 21:51:56.001622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1773a9ed2283'
down_revision = '33c87310b018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('references', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'references')
    # ### end Alembic commands ###
