"""empty message

Revision ID: 21f00e56cbeb
Revises: fac80015b642
Create Date: 2022-06-17 14:07:39.398929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f00e56cbeb'
down_revision = 'fac80015b642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('specification', sa.String(length=140), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('textdump', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource')
    # ### end Alembic commands ###
