"""empty message

Revision ID: 2cd7063dbd27
Revises: 0a1aea321a20
Create Date: 2022-08-18 19:35:12.164730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd7063dbd27'
down_revision = '0a1aea321a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_to_course', 'resource_name',
                    nullable=True, new_column_name='name')
    op.alter_column('resource_to_course', 'resource_part_name',
                    nullable=True, new_column_name='part_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_to_course', 'name',
                    nullable=True, new_column_name='resource_name')
    op.alter_column('resource_to_course', 'part_name',
                    nullable=True, new_column_name='resource_part_name')
    # ### end Alembic commands ###
