"""empty message

Revision ID: 2d9d9d53ba20
Revises: 783fb67a6c3d
Create Date: 2022-08-18 23:05:31.932451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9d9d53ba20'
down_revision = '783fb67a6c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_to_course', 'is_divided_to_parts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_to_course', sa.Column('is_divided_to_parts', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
