"""empty message

Revision ID: 2dfcc596d361
Revises: b1c6c33f6d09
Create Date: 2023-02-18 19:42:06.731842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfcc596d361'
down_revision = 'b1c6c33f6d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'instructor')
    op.drop_column('resource', 'grouping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('grouping', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('instructor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
