"""empty message

Revision ID: 2f34d9af92d9
Revises: 367c06d8cf6e
Create Date: 2022-09-16 11:37:58.659538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f34d9af92d9'
down_revision = '367c06d8cf6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('resource', sa.Column('tab', sa.String(length=10), nullable=True))
    op.add_column('resource', sa.Column('order_in_tab', sa.Integer(), nullable=True))
    op.add_column('resource', sa.Column('header', sa.String(length=140), nullable=True))
    op.add_column('resource', sa.Column('rname', sa.String(length=140), nullable=True))
    op.add_column('resource', sa.Column('rname_part', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'rname_part')
    op.drop_column('resource', 'rname')
    op.drop_column('resource', 'header')
    op.drop_column('resource', 'order_in_tab')
    op.drop_column('resource', 'tab')
    op.drop_column('resource', 'course_id')
    # ### end Alembic commands ###
