"""empty message

Revision ID: 33c87310b018
Revises: 2dfcc596d361
Create Date: 2023-02-19 11:47:30.976265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c87310b018'
down_revision = '2dfcc596d361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_in_recycle_bin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_in_recycle_bin')
    # ### end Alembic commands ###
