"""empty message

Revision ID: 433dd399d33d
Revises: 4651c6155455
Create Date: 2023-02-17 16:19:16.860712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433dd399d33d'
down_revision = '4651c6155455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('course_institute', sa.String(length=140), nullable=True))
    op.add_column('resource', sa.Column('course_institute_id', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'course_institute_id')
    op.drop_column('resource', 'course_institute')
    # ### end Alembic commands ###
