"""empty message

Revision ID: 4651c6155455
Revises: c2002ceb0008
Create Date: 2023-01-25 15:15:54.521811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4651c6155455'
down_revision = 'c2002ceb0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('grouping', sa.String(length=50), nullable=True))
    op.add_column('resource', sa.Column('instructor', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'instructor')
    op.drop_column('resource', 'grouping')
    # ### end Alembic commands ###
