"""empty message

Revision ID: 4bb61a073aa9
Revises: 21ea50e15f7d
Create Date: 2022-06-24 21:32:30.169982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb61a073aa9'
down_revision = '21ea50e15f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('creator', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'creator')
    # ### end Alembic commands ###
