"""empty message

Revision ID: 4c99440a4de4
Revises: 2f34d9af92d9
Create Date: 2022-09-16 12:35:34.980619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c99440a4de4'
down_revision = '2f34d9af92d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_to_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_to_course',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_in_tab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('header', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('rname', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('rname_part', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('tab', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resource_to_course_pkey')
    )
    # ### end Alembic commands ###
