"""empty message

Revision ID: 521f6090c6a4
Revises: d3ed60c2a7e5
Create Date: 2022-08-28 22:10:06.554701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521f6090c6a4'
down_revision = 'd3ed60c2a7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'name',
                    nullable=True, new_column_name='course_name')
    op.alter_column('subject', 'name',
                    nullable=True, new_column_name='subject_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'course_name',
                    nullable=True, new_column_name='name')
    op.alter_column('subject', 'subject_name',
                    nullable=True, new_column_name='name')
    # ### end Alembic commands ###
