"""empty message

Revision ID: 5cb631064cfb
Revises: 8405d132220c
Create Date: 2022-09-28 14:46:22.714709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb631064cfb'
down_revision = '8405d132220c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'tab')
    op.drop_column('resource', 'rname_part')
    op.drop_column('resource', 'header')
    op.drop_column('resource', 'order_in_tab')
    op.drop_column('resource', 'rname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('rname', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('order_in_tab', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('header', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('rname_part', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('tab', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
