"""empty message

Revision ID: 72449cf7a910
Revises: 5cb631064cfb
Create Date: 2022-10-01 15:06:03.492575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72449cf7a910'
down_revision = '5cb631064cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_solution_partial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_solution_partial')
    # ### end Alembic commands ###
