"""empty message

Revision ID: 783fb67a6c3d
Revises: 2cd7063dbd27
Create Date: 2022-08-18 21:10:17.892418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783fb67a6c3d'
down_revision = '2cd7063dbd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_to_course', 'name',
                    nullable=True, new_column_name='rname')
    op.alter_column('resource_to_course', 'part_name',
                    nullable=True, new_column_name='rname_part')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_to_course', 'rname',
                    nullable=True, new_column_name='name')
    op.alter_column('resource_to_course', 'rname_part',
                    nullable=True, new_column_name='part_name')
    # ### end Alembic commands ###
