"""empty message

Revision ID: 7c4ea0b6a2e4
Revises: d993688dae33
Create Date: 2022-10-17 11:05:44.110274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4ea0b6a2e4'
down_revision = 'd993688dae33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('num_comments', sa.Integer(), nullable=True))
    op.add_column('resource', sa.Column('last_comment', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'last_comment')
    op.drop_column('resource', 'num_comments')
    # ### end Alembic commands ###
