"""empty message

Revision ID: 7f60656dbef4
Revises: ede11c9d490e
Create Date: 2022-08-18 01:04:05.943130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f60656dbef4'
down_revision = 'ede11c9d490e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_to_course', sa.Column('tab', sa.String(length=10), nullable=True))
    op.drop_column('resource_to_course', 'is_in_exams_tab')
    op.drop_column('resource_to_course', 'is_in_semester_tab')
    op.drop_column('resource_to_course', 'is_in_archive_tab')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_to_course', sa.Column('is_in_archive_tab', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('resource_to_course', sa.Column('is_in_semester_tab', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('resource_to_course', sa.Column('is_in_exams_tab', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('resource_to_course', 'tab')
    # ### end Alembic commands ###
