"""empty message

Revision ID: 90dcf2a08c47
Revises: fdf0f1c76c30
Create Date: 2022-09-27 08:55:49.663092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dcf2a08c47'
down_revision = 'fdf0f1c76c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'likes')
    op.drop_column('resource', 'type')
    # ### end Alembic commands ###
