"""empty message

Revision ID: 9b5f44616153
Revises: 553a7e619038
Create Date: 2022-09-12 20:14:32.301981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b5f44616153'
down_revision = '553a7e619038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'textdump')
    op.drop_column('resource', 'deadline_date')
    op.drop_column('resource', 'deadline_week')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('deadline_week', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('deadline_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('textdump', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
