"""empty message

Revision ID: a1906b37d3e1
Revises: b4a3b9ca1c4a
Create Date: 2022-09-26 19:17:52.588838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1906b37d3e1'
down_revision = 'b4a3b9ca1c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_official', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_official')
    # ### end Alembic commands ###
