"""empty message

Revision ID: a3f5843ae82b
Revises: 433dd399d33d
Create Date: 2023-02-18 19:13:01.804475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f5843ae82b'
down_revision = '433dd399d33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('subject',
    sa.Column('subject_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('subject_id', name='subject_pkey')
    )
    # ### end Alembic commands ###
