"""empty message

Revision ID: adeb319133f6
Revises: dedfc113eb78
Create Date: 2022-08-16 21:58:00.936395

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'adeb319133f6'
down_revision = 'dedfc113eb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'specification',
                    nullable=True, new_column_name='solution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'solution', nullable=True,
                    new_column_name='specification')
    # ### end Alembic commands ###
