"""empty message

Revision ID: b4a3b9ca1c4a
Revises: 4c99440a4de4
Create Date: 2022-09-26 19:07:00.043400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a3b9ca1c4a'
down_revision = '4c99440a4de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('display_name', sa.String(length=140), nullable=True))
    op.add_column('resource', sa.Column('semester', sa.String(length=30), nullable=True))
    op.add_column('resource', sa.Column('deadline_week', sa.String(length=140), nullable=True))
    op.add_column('resource', sa.Column('deadline_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'deadline_date')
    op.drop_column('resource', 'deadline_week')
    op.drop_column('resource', 'semester')
    op.drop_column('resource', 'display_name')
    # ### end Alembic commands ###
