"""empty message

Revision ID: c2002ceb0008
Revises: f365f4b41ddb
Create Date: 2023-01-21 11:46:21.525799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2002ceb0008'
down_revision = 'f365f4b41ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('recording_comment', sa.String(length=100), nullable=True))
    op.add_column('resource', sa.Column('recording2_comment', sa.String(length=100), nullable=True))
    op.add_column('resource', sa.Column('recording3_comment', sa.String(length=100), nullable=True))
    op.add_column('resource', sa.Column('recording4_comment', sa.String(length=100), nullable=True))
    op.add_column('resource', sa.Column('recording5_comment', sa.String(length=100), nullable=True))
    op.drop_column('resource', 'recording3_start')
    op.drop_column('resource', 'recording3_end')
    op.drop_column('resource', 'recording_start')
    op.drop_column('resource', 'recording5_end')
    op.drop_column('resource', 'recording2_end')
    op.drop_column('resource', 'recording2_start')
    op.drop_column('resource', 'recording_end')
    op.drop_column('resource', 'recording4_end')
    op.drop_column('resource', 'recording4_start')
    op.drop_column('resource', 'recording5_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('recording5_start', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording4_start', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording4_end', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording_end', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording2_start', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording2_end', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording5_end', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording_start', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording3_end', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('recording3_start', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('resource', 'recording5_comment')
    op.drop_column('resource', 'recording4_comment')
    op.drop_column('resource', 'recording3_comment')
    op.drop_column('resource', 'recording2_comment')
    op.drop_column('resource', 'recording_comment')
    # ### end Alembic commands ###
