"""empty message

Revision ID: d993688dae33
Revises: 72449cf7a910
Create Date: 2022-10-14 16:59:33.922607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd993688dae33'
down_revision = '72449cf7a910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('discord_invite', sa.String(length=200), nullable=True))
    op.drop_column('resource', 'is_official')
    op.drop_column('resource', 'deadline_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('deadline_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('is_official', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('course', 'discord_invite')
    # ### end Alembic commands ###
