"""empty message

Revision ID: d9ddebf75e32
Revises: 
Create Date: 2022-08-16 21:00:48.811157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ddebf75e32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=140), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('resource',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('link', sa.String(length=500), nullable=True),
                    sa.Column('solution', sa.String(
                        length=500), nullable=True),
                    sa.Column('creator', sa.String(length=140), nullable=True),
                    sa.Column('subject', sa.Text(), nullable=True),
                    sa.Column('textdump', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('resource_to_course',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.Column('resource_id', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(
                        length=140), nullable=True),
                    sa.Column('importance', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subject',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=500), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password_hash', sa.String(
                        length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user',
                    ['username'], unique=True)
    op.create_table('post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.String(length=140), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_post_timestamp'), 'post',
                    ['timestamp'], unique=False)
    op.create_table('resource_to_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('resource_id', sa.Integer(), nullable=True),
                    sa.Column('done', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_to_user')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('subject')
    op.drop_table('resource_to_course')
    op.drop_table('resource')
    op.drop_table('course')
    # ### end Alembic commands ###
