"""empty message

Revision ID: d9dfbf55a264
Revises: af69b70b566d
Create Date: 2022-08-15 20:55:23.424558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9dfbf55a264'
down_revision = 'af69b70b566d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_timestamp', table_name='comment')
    op.drop_table('comment')
    op.add_column('resource_to_course', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_to_course', 'order')
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('parent_comment', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('pinned', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_timestamp', 'comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###
