"""empty message

Revision ID: ede11c9d490e
Revises: f75e1d99a9a5
Create Date: 2022-08-17 20:07:13.000627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede11c9d490e'
down_revision = 'f75e1d99a9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_to_course', 'order',
                    nullable=True, new_column_name='order_in_tab')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_to_course', 'order_in_tab',
                    nullable=True, new_column_name='order')
    # ### end Alembic commands ###
