"""empty message

Revision ID: f365f4b41ddb
Revises: 0180c01c4b92
Create Date: 2023-01-21 11:15:57.302092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f365f4b41ddb'
down_revision = '0180c01c4b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('recording_start', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording_end', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording2', sa.String(length=500), nullable=True))
    op.add_column('resource', sa.Column('recording2_start', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording2_end', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording3', sa.String(length=500), nullable=True))
    op.add_column('resource', sa.Column('recording3_start', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording3_end', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording4', sa.String(length=500), nullable=True))
    op.add_column('resource', sa.Column('recording4_start', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording4_end', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording5', sa.String(length=500), nullable=True))
    op.add_column('resource', sa.Column('recording5_start', sa.String(length=20), nullable=True))
    op.add_column('resource', sa.Column('recording5_end', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'recording5_end')
    op.drop_column('resource', 'recording5_start')
    op.drop_column('resource', 'recording5')
    op.drop_column('resource', 'recording4_end')
    op.drop_column('resource', 'recording4_start')
    op.drop_column('resource', 'recording4')
    op.drop_column('resource', 'recording3_end')
    op.drop_column('resource', 'recording3_start')
    op.drop_column('resource', 'recording3')
    op.drop_column('resource', 'recording2_end')
    op.drop_column('resource', 'recording2_start')
    op.drop_column('resource', 'recording2')
    op.drop_column('resource', 'recording_end')
    op.drop_column('resource', 'recording_start')
    # ### end Alembic commands ###
