"""empty message

Revision ID: f757e4fbd312
Revises: eb61f30a776f
Create Date: 2022-09-05 20:12:43.214118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f757e4fbd312'
down_revision = 'eb61f30a776f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('maintainer_email', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'maintainer_email')
    # ### end Alembic commands ###
