"""empty message

Revision ID: f75e1d99a9a5
Revises: 033e2affbe9b
Create Date: 2022-08-17 19:23:05.406021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75e1d99a9a5'
down_revision = '033e2affbe9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_to_course', sa.Column(
        'is_in_semester_tab', sa.Boolean(), nullable=True))
    op.add_column('resource_to_course', sa.Column(
        'is_in_exams_tab', sa.Boolean(), nullable=True))
    op.add_column('resource_to_course', sa.Column(
        'is_in_archive_tab', sa.Boolean(), nullable=True))
    op.add_column('resource_to_course', sa.Column(
        'header', sa.String(length=140), nullable=True))
    op.add_column('resource_to_course', sa.Column(
        'resource_name', sa.String(length=140), nullable=True))
    op.add_column('resource_to_course', sa.Column(
        'is_divided_to_parts', sa.Boolean(), nullable=True))
    op.add_column('resource_to_course', sa.Column(
        'is_first_part', sa.Boolean(), nullable=True))
    op.add_column('resource_to_course', sa.Column(
        'resource_part_name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_to_course', 'resource_part_name')
    op.drop_column('resource_to_course', 'is_first_part')
    op.drop_column('resource_to_course', 'is_divided_to_parts')
    op.drop_column('resource_to_course', 'resource_name')
    op.drop_column('resource_to_course', 'header')
    op.drop_column('resource_to_course', 'is_in_archive_tab')
    op.drop_column('resource_to_course', 'is_in_exams_tab')
    op.drop_column('resource_to_course', 'is_in_semester_tab')
    # ### end Alembic commands ###
